import { Poppins } from "next/font/google";
import "../globals.css";
import { DashboardNav } from "@/components/dashboard-nav";
import { DashboardHeader } from "@/components/dashboard-header";


const poppins = Poppins({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ['600']
})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
        <div className="min-h-screen flex">
          <div className="w-64 h-screen sticky top-0 left-0 bg-white shadow-md">
            <DashboardNav />
          </div>

          <div className="flex-1 flex flex-col">
            <div className="sticky top-0 z-10 bg-white shadow-md">
              <DashboardHeader />
            </div>

            <div className="flex-1 p-4">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
